fname = input("First name: ")
lname = input("Last name: ")
email = input("Email address: ")
phone = input("Phone Number: ")
job = input("Job title: ")
idnumber = input("ID Number: ")

print()
print("The ID Card is:")
print("---------------------------------------")
print(f"{lname.upper()}, {fname.capitalize()}")
print(f"{job.title()}")
print(f"ID: {idnumber}")
print()
print({email.lower()})
print(phone)
print("---------------------------------------")